// Run the real UI with a small DOM and API harness; no network or packages needed.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Element{constructor(){this.tagName='DIV';this.value='';this.children=[];this.dataset={};this.readyState=0;this.paused=true}append(...xs){this.children.push(...xs)}replaceChildren(...xs){this.children=xs}setAttribute(k,v){this[k]=v}removeAttribute(k){delete this[k]}load(){}pause(){this.paused=true}play(){this.paused=false;return Promise.resolve()}focus(){this.focused=true}blur(){this.focused=false}}
const elements={},listeners={},requests=[];let failSave=false,holdSave=null;
const manifest=id=>({id,clip_start_frame:100,clip_end_frame_exclusive:400,sampling_fps_numerator:3,sampling_fps_denominator:1});
const meta={question:'Question?',choices:['one','two','three','four'],right_answer:'A',answer:'one',evidence_intervals:[{label:'Anchor',start_frame_in_source:130},{label:'Answer',start_frame_in_source:160}]};
const rows=['one','two'].map(id=>({id,status:'pending'}));
const context=vm.createContext({console,URL,Blob,window:{addEventListener:()=>{}},document:{querySelector:()=>null,getElementById:id=>elements[id]??=new Element(),createElement:()=>new Element(),addEventListener:(key,fn)=>listeners[key]=fn},fetch:async(path,options)=>{const url=new URL(path,'https://test.invalid');let result;if(url.pathname==='/api/items')result={version:'1',items:rows};if(url.pathname==='/api/item')result={version:'1',manifest:manifest(url.searchParams.get('id')),meta,warnings:[]};if(url.pathname==='/api/media')result={url:'https://test.invalid/video.mp4'};if(url.pathname==='/api/review'){requests.push(JSON.parse(options.body));if(holdSave)await holdSave;if(failSave)return {ok:false,json:async()=>({error:'Save failed'})};result={}}return {ok:true,json:async()=>result}}});
vm.runInContext(fs.readFileSync('app/static/ui.js','utf8'),context);
const run=code=>vm.runInContext(code,context),tick=()=>new Promise(resolve=>setImmediate(resolve));
function key(key,target=new Element(),extra={}){let prevented=false;listeners.keydown({key,target,preventDefault:()=>prevented=true,...extra});return prevented}
(async()=>{await tick();assert.equal(run('selected.manifest.id'),'one');assert.equal(run('evidenceTime(selected, selected.meta.evidence_intervals[0])'),10);assert.throws(()=>run('evidenceTime(selected,{start_frame_in_source:99})'));
key('e');await tick();assert.equal(run('pendingSeek'),10);elements.video.readyState=1;elements.video.onloadedmetadata();assert.equal(elements.video.currentTime,10);key('e');await tick();assert.equal(elements.video.currentTime,20);
const input=new Element();input.tagName='TEXTAREA';key('a',input);key('a',undefined,{repeat:true});key('r',undefined,{ctrlKey:true});await tick();assert.equal(requests.length,0);
key('c');assert.equal(elements.comment.focused,true);key('Escape',Object.assign(elements.comment,{tagName:'TEXTAREA'}));assert.equal(elements.comment.focused,false);
failSave=true;key('a');await tick();assert.equal(run('selected.manifest.id'),'one');assert.equal(elements.error.textContent,'Save failed');assert.equal(requests[0].checks.gold_supported,true);
failSave=false;let release;holdSave=new Promise(resolve=>release=resolve);key('r');key('a');key('ArrowRight');await tick();assert.equal(requests.length,2);assert.equal(run('selected.manifest.id'),'one');release();await tick();assert.equal(run('selected.manifest.id'),'two');assert.equal(requests[1].status,'bad');assert.equal(requests[1].version,'1');holdSave=null;
key('a');await tick();assert.equal(run('selected.manifest.id'),'two');assert.match(elements.saved.textContent,/最後/);assert.equal(requests.length,3);console.log('UI shortcuts, source-frame seeking, input guards, save failure, double-submit and final item: passed');})().catch(e=>{console.error(e);process.exitCode=1});
